# Dockerfile.ui
FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY ui/package.json ./ui/

# Install dependencies
RUN pnpm install --frozen-lockfile

# Copy the UI source code
COPY ui ./ui

# Build UI
WORKDIR /app/ui
RUN pnpm run build

# Expose port and start
EXPOSE 3000
CMD ["pnpm", "run", "start"]
